image: maven:3.8.6-jdk-11

default:
  tags:
    - java
    - maven

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -noverify"
  RD_TOKEN: $RD_TOKEN

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - sync2
  - build
  - deploy_artifactory
  - sync1

sync_to_github:
  stage: sync1
  #image: alpine/git # Use an image with Git pre-installed
  #before_script:
  script:
    - git config --global user.email "donghongpei@gmail.com"
    - git config --global user.name "DonPei"
    - git remote add github "https://oauth2:${GITHUB_TOKEN}@github.com/DonPei/groovy.git" # Replace with your GitHub repo URL
    - git push --force github HEAD:main # Adjust 'main' to your desired branch
  only:
    - main # Or the branch you want to trigger the sync from

sync_to_AEMaaCS:
  stage: sync2
  script:
    - git config --global user.email "dpei1@mdanderson.org"
    - git config --global user.name "d-pei1-mdanderson-org"
    - git remote add adobe https://${CLOUD_USER}:${CLOUD_PASSWORD}@git.cloudmanager.adobe.com/mdanderson/philanthropy/
    - git push adobe main
  only:
    - main # Or the branch you want to trigger the sync from

mvn:build:
  stage: build
  script:
    - echo "Maven snapshot build started now."
    - mvn $MAVEN_CLI_OPTS $MVN_OPTS package
    - echo "Maven snapshot build completed."

mvn:deploy_artifactory:
  stage: deploy_artifactory
  environment: develop
  dependencies:
    - mvn:build
  script:
    - echo "Start to deploy development to Artifactory."
    - mvn $MAVEN_CLI_OPTS $MVN_OPTS deploy
    - echo "Deployed successfully to Artifactory."
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
